name: Staging

on:
  pull_request:
    branches:
      - staging
    types:
      - opened
      - synchronize
      - reopened

jobs:
  staging-mvn-test-build:
    name: staging mvn test and build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean test

  staging-docker-build-push:
    name: staging docker build and push
    runs-on: ubuntu-22.04
    needs: staging-mvn-test-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Extract project version from pom.xml
        run: echo "PROJECT_VERSION=$(mvn help:evaluate \"-Dexpression=project.version\" -q -DforceStdout)" >> $GITHUB_ENV

      - name: Extract Pull Request Number
        run: echo "PR_NUMBER=$(echo ${{ github.event.pull_request.number }})" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/qosocial-springboot-monolith:${{ env.PROJECT_VERSION }}-pr${{ env.PR_NUMBER }},
            ${{ secrets.DOCKERHUB_USERNAME }}/qosocial-springboot-monolith:latest